server: 
  port: 9001
spring: 
  application:  
    name: nlmeetingroom-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.55.101.174/meetingroom?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: false
  rabbitmq:
      host: 114.55.101.174
      username: admin
      password: admin
      virtual-host: my_vhost
jwt:
  config:
    key: llz123456
    ttl: 360000